name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show working directory and tree (debug)
        run: |
          echo "PWD=$(pwd)"
          echo "=== Top level ==="
          ls -la
          echo "=== app folder ==="
          ls -la app || true
          echo "=== show app/Dockerfile ==="
          if [ -f app/Dockerfile ]; then
            sed -n '1,200p' app/Dockerfile
          else
            echo "app/Dockerfile NOT FOUND"
          fi

      - name: Verify secrets are present (debug)
        run: |
          [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ] || (echo "Missing DOCKERHUB_USERNAME" && exit 1)
          [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ] || (echo "Missing DOCKERHUB_TOKEN" && exit 1)
          echo "Secrets look present ✅"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudcart:latest
